export enum ChatEvent {
  NEW_MESSAGE = "NEW_MESSAGE",
  CREATED_CHAT = "CREATED_CHAT",
  CONNECT_USER = "CONNECT_USER",
  USER_ONLINE = "USER_ONLINE",
  USER_OFFLINE = "USER_OFFLINE",
  READ_MESSAGE = "READ_MESSAGE"
}
