export enum ACTIONS_MESSAGE {
  NEW_MESSAGE = "NEW_MESSAGE",
  UPDATE_LAST_MESSAGE = "UPDATE_LAST_MESSAGE",
  READ_MESSAGES = "READ_MESSAGES",
  UPDATE_COUNTERS_CHATS = "UPDATE_COUNTERS_CHATS"
}

export enum ACTIONS_CHAT {
  CHAT_CLEAR_FILES = "CHATS/CLEAR_FILES",
  SELECT_CHAT = "CHATS/SELECT_CHAT"
}
